### ISSUE TITLE
monorepo

### ISSUE THREAD

**Issue by levino** [HiDeoo/starlight-blog#20]
### Is your feature request related to a problem?

I really like your work @HiDeoo. While working with your code, I had some issues, especially since you are using some dependencies on your own code like your personal eslint configs etc. I found it a bit cumbersome to have to search for these on github to understand what is inside of them. It would be way more convenient, if they would be already on my disk, which would mean a monorepo. I think that approach would work quite well for a lot of your packages, for example also `starlight-typedoc` etc. Since you are already using pnpm workspaces, you already seem to know the gist. I can recommend `turbo` and `changesets` as additional tools to speed up things.

### Describe the solution you'd like

See above.

**Comment by HiDeoo** [comment]
Thanks for your suggestions.

I think for the moment I would like to keep things scoped and separated as much as possible rather than having a way bigger monorepo. I also don't think we are at the point where we need to use something like turbo, especially since we are not building anything.

That being said, this may be an idea to revisit in the future, maybe once everything is Starlight plugin based or something like that. 👍
