### ISSUE TITLE
Author's picture isn't optimised

### ISSUE THREAD

**Issue by ematipico** [HiDeoo/starlight-blog#52]
### Describe the bug

The dev toolbar complains about the images not being optimized 
<img width="446" alt="Screenshot 2024-06-15 at 14 19 01" src="https://github.com/HiDeoo/starlight-blog/assets/602478/96840082-64fb-4eab-ae1d-35bf9ad60607">

### To Reproduce

Define an author with a remote URL:

```js
					ema: {
						"name": "Emanuele Stoppa",
						"picture": "https://avatars.githubusercontent.com/u/602478?v=4",
						"url": "https://twitter.com/ematipico"
					}
```

### Expected behavior

I expect no warnings from the dev toolbar

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report, super appreciated. I totally missed this one and I was using an Astro version not reporting this error.

This will be fixed in the next version of the plugin but I want to push a few more changes before releasing it.

Note that on some pages (blog posts and tags listing), another error ([`perf-use-loading-lazy`](https://github.com/withastro/astro/blob/233fee9c04ba5d9cbcda13a93f9f6d8ecd5794d8/packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/perf.ts#L29-L46)) may appear based on the number/length of posts, height of the page, etc.

I cannot reliably handle this error as it's based on various factors so I'll probably ask Erika/open an issue about it as I don't think the rule in its current form can handle this case.
