### ISSUE TITLE
Astro's `srcDir` seems to be not supported

### ISSUE THREAD

**Issue by roll** [HiDeoo/starlight-blog#60]
### Describe the bug

The plugin doesn't seem to be taking into an account `srcDir`

### To Reproduce

1. Have a config like this
```js
// https://astro.build/config
export default defineConfig({
  srcDir: ".",
}
```
2. Setup the blog
3. Run `astro build`
4. Fail with `[vite]: Rollup failed to resolve import "/src/content/config.ts" from "virtual:starlight/collection-config".`

### Expected behavior

It builds instead of failing

### How often does this bug happen?

Every time

### Additional Context

A temporary fix is just to have `src/content/config.ts` copy as well

**Comment by HiDeoo** [comment]
Thanks for the report 🙌 

This turns out to be an issue in Starlight and I've opened https://github.com/withastro/starlight/pull/2054 to fix the issue.

**Comment by HiDeoo** [comment]
Starlight [`0.24.5`](https://github.com/withastro/starlight/releases/tag/@astrojs/starlight@0.24.5) was just released with the fix for this issue.

I just tested locally with a custom `srcDir` using that latest Starlight version and now the build works fine as expected.

Thanks again for your report 🙌

**Comment by roll** [comment]
Thanks for taking car of it!
