### ISSUE TITLE
RSS Feed Includes Astro Imports

### ISSUE THREAD

**Issue by IMax153** [HiDeoo/starlight-blog#92]
### Describe the bug

When utilizing MDX features to import `.astro` components into blog pages (for things like YouTube / Twitter embeds), the RSS feed includes the imports instead of just using the rendered page content.

![Image of an RSS reader displaying Astro imports in the RSS feed](https://github.com/user-attachments/assets/a8b0e5f3-6663-435f-b078-e060a62df726)

This is also plainly visible in the XML for the RSS feed: https://effect.website/blog/rss.xml

### To Reproduce

1. Visit https://effect.website/blog/rss.xml
2. Observe the inclusion of `.astro` imports in the generated RSS content

The configuration for our site is here: https://github.com/Effect-TS/website/blob/main/content/astro.config.ts

### Expected behavior

The RSS feed should only include rendered content and should not include things such as MDX imports.

### How often does this bug happen?

Every time

### System Info

- All OS'es
- All browsers 
- `starlight-blog`: `v0.14.1`

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

The issue was a bit of a duplicate of #65 as the RSS feed was due for a refactor for a while now as the Astro Container API was at a very early stage when the RSS feed was implemented and I decided at the time to not use it. The feature is still experimental but more mature and stable now so I've updated the RSS feed to use this API and the issue should now be fixed in the latest version of the plugin.

**Comment by IMax153** [comment]
@HiDeoo Thank you so much! I can confirm that upgrading has fixed our issue 👍
